[package]
name = "counter-call"
version = "0.1.0"
authors = ["Michael Birch <birchmd@casperlabs.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
contract = { package = "casper-contract", version = "0.7.0" }
types = { package = "casper-types", version = "0.7.0" }